export const ERROR_CODES = {
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  AUTH_ERROR: 'AUTH_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
} as const;

export type ErrorCodeValue = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
